# Generated by Django 4.1.2 on 2022-10-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_description_movie_movie_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='owner',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
